[package]
name = "tiko-database"
version.workspace = true
edition.workspace = true

[dependencies]
argon2 = "0.5.3"
fake = "5.1.0"
rand_core = { version = "0.6", features = ["getrandom"] }
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
